services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
                NEXT_PUBLIC_GOOGLE_OAUTH_URL: ${NEXT_PUBLIC_GOOGLE_OAUTH_URL}
                NEXT_PUBLIC_FILE_URL: ${NEXT_PUBLIC_FILE_URL}
                NEXT_PUBLIC_TWITCH_CHANNEL: ${NEXT_PUBLIC_TWITCH_CHANNEL}
        environment:
            SERVER_API_URL: ${SERVER_API_URL}
            COOKIE_DOMAIN: ${COOKIE_DOMAIN}
        ports:
            - '3001:3000'
        networks:
            - distruct-net

networks:
    distruct-net:
        external: true
